//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch FileSync.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_PROGRESS           103
#define IDC_EDITLINE                    104
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        130
#define IDR_DIRCOMPFRAME                132
#define IDB_OPEN                        133
#define IDB_SAVE_DIS                    135
#define IDB_SAVE                        136
#define IDD_PREF                        139
#define ID_VIEW_DIRCOMP                 141
#define ID_FILE_OPENDIRLEFT             142
#define ID_FILE_OPENDIRRIGHT            143
#define ID_VIEW_FILESYNC                146
#define ID_VIEW_REFRESH                 147
#define IDR_VIEWISO                     148
#define ID_VIEW_INCLUDESUBDIRS          149
#define IDR_VIEWTEXT                    151
#define IDR_VIEWZIP                     152
#define IDR_VIEWDIR                     153
#define IDR_VIEWTEXT_R                  156
#define IDR_VIEWDIR_R                   159
#define IDR_VIEWHEX                     161
#define IDD_ASSOC                       163
#define ID_VIEW_ASSOCIATIONS            164
#define IDD_OVERWRITE_NEWER             165
#define ID_VIEW_COLORS                  169
#define IDD_COLORS                      170
#define IDB_TREEIMAGES                  171
#define IDR_MENU_TYPE                   174
#define ID_TYPE_TEXT                    175
#define ID_TYPE_HEX                     176
#define IDD_OPEN_EXT                    177
#define IDR_MENU_DIR                    179
#define ID_DIR_EXPANDALL                180
#define IDR_VIEWXML                     182
#define ID_TYPE_XML                     183
#define IDD_DIALOG_PROGRESS             183
#define IDD_REPLACE                     184
#define IDR_TOOL_SEARCH                 185
#define IDB_OPENDIR                     187
#define IDB_MODE_R                      189
#define IDB_MODE_RY                     190
#define IDB_MODE_GY                     191
#define IDB_MODE_G                      192
#define IDB_MODE_DIS                    193
#define IDB_CHECK                       195
#define IDB_OPEN_MENU                   196
#define IDB_OPENDIR_MENU                197
#define IDB_DIRCOMP                     198
#define IDB_FILECOMP                    199
#define IDC_LIST                        1000
#define IDC_BIGICON                     1000
#define IDC_LIST_RIGHT                  1001
#define IDC_SCROLL_HORIZ                1002
#define IDC_SCROLL_VERT                 1003
#define IDC_EDIT_DIR_LEFT               1004
#define IDC_EDIT_DIR_RIGHT              1005
#define IDC_TOOL_LEFT                   1006
#define IDC_TOOL_RIGHT                  1007
#define ID_FILE_OPEN_LEFT               1008
#define ID_FILE_SAVE_LEFT               1009
#define ID_FILE_OPEN_RIGHT              1010
#define ID_FILE_SAVE_RIGHT              1011
#define IDC_EDIT_TABSIZE                1012
#define IDC_CHECK_IGN_SPACES            1014
#define IDC_CHECK_UNIX_LEFT             1015
#define IDC_CHECK_UNIX_RIGHT            1016
#define IDC_SPIN_TABSIZE                1017
#define IDC_SPIN_SYNCLINES              1018
#define IDC_CHECK_RO_LEFT               1019
#define IDC_CHECK_RO_RIGHT              1020
#define IDC_CHECK_FRO_LEFT              1021
#define IDC_CHECK_FRO_RIGHT             1022
#define IDC_LIST_EXT                    1023
#define IDC_EDIT_EXT                    1024
#define IDC_BUTTON_DEL                  1025
#define IDC_BUTTON_ADD                  1026
#define IDC_BUTTON_DEF                  1026
#define IDC_BUTTON_C1                   1027
#define IDC_BUTTON_C2                   1028
#define IDC_BUTTON_C3                   1029
#define IDC_BUTTON_C4                   1030
#define IDC_COMBO_VIEW                  1030
#define IDC_BUTTON_C5                   1031
#define IDC_BUTTON_OPEN_LEFT            1031
#define IDC_BUTTON_OPEN_RIGHT           1032
#define IDC_COMBO_TYPE                  1033
#define IDC_COMBO_CSET_L                1033
#define IDC_STATIC_VERSION              1034
#define IDC_COMBO_CSET_R                1034
#define IDC_PROGRESS_CTRL               1036
#define IDC_STATIC_TEXT1                1037
#define IDC_STATIC_TEXT2                1038
#define IDC_STATIC_TEXT3                1039
#define IDC_SEARCH_C                    1039
#define IDC_LISTMODE                    1040
#define ID_FILE_SAVE_LEFT_AS            1041
#define ID_FILE_SAVE_RIGHT_AS           1042
#define ID_EDIT_INSERTBEFORE            32769
#define ID_EDIT_INSERTAFTER             32770
#define ID_EDIT_REPLACESEL              32771
#define ID_EDIT_DELETE                  32772
#define ID_VIEW_PREV_DIFF               32775
#define ID_VIEW_NEXT_DIFF               32776
#define ID_EDIT_PREF                    32778
#define ID_EDIT_PREV                    32779
#define ID_EDIT_NEXT                    32780
#define ID_VIEW_EXPLORER                32782
#define ID_TYPE_RW                      32786
#define ID_TYPE_OPEN                    32787
#define ID_DIR_COLLAPSE                 32788
#define ID_DIR_EXPANDPARTIAL            32789
#define ID_DIR_SETEQUAL                 32790
#define ID_SEARCH_B                     32792
#define ID_SEARCH_F                     32794
#define ID_DIR_SELECTDIFFS              32795
#define ID_VIEW_TEXT                    32796
#define ID_FILE_MODELEFT                32797
#define ID_FILE_MODERIGHT               32798
#define ID_VIEW_CHECKLEFT               32799
#define ID_VIEW_CHECKRIGHT              32800
#define ID_EDIT_DEL_LINES               32802
#define ID_VIEW_HEX                     32803
#define ID_HELP_CONTENTS                32804
#define ID_HELP_CONTEXT                 32805
#define ID_VIEW_XML                     32806
#define ID_SORT_NAME                    32807
#define ID_SORT_MKS                     32808
#define ID_SORT_LEFT_SIZE               32809
#define ID_SORT_LEFT_SIZE_DESC          32810
#define ID_SORT_LEFT_TIME               32811
#define ID_SORT_LEFT_TIME_DESC          32812
#define ID_SORT_RIGHT_SIZE              32813
#define ID_SORT_RIGHT_SIZE_DESC         32814
#define ID_SORT_RIGHT_TIME              32815
#define ID_SORT_RIGHT_TIME_DESC         32816
#define ID_DIR_FREE                     32817
#define ID_VIEW_PROJECT                 32818
#define ID_VIEW_LINK                    32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
